name: Pull Request tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: plugin/tests (ubuntu-latest, Node v${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Run all tests
        run: yarn test:all

      - name: Check for TypeScript errors
        run: yarn build:ts

  lint:
    name: plugin/lint (ubuntu-latest, Node v22)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Check TypeScript types
        run: yarn build:ts --noEmit

  docs-build:
    name: docs/build (ubuntu-latest, Node v18)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install Root Dependencies & Build Plugin
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Install Docs Dependencies
        run: |
          cd docs
          yarn install --frozen-lockfile

      - name: Build Documentation Site
        run: |
          cd docs
          yarn build
